[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bincode = "1.3.3"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
